name: compile pRIblast (release)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up mpi and openmp
      run: >
        sudo apt-get update -y &&
        sudo apt-get install -y build-essential &&
        sudo apt-get install -y libopenmpi-dev openmpi-bin libomp-dev
    - name: build priblast (release)
      run: make BUILD=release
      working-directory: ${{ github.workspace }}
