name: compile gnu
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Makefile'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Makefile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: set up mpi and openmp
      run: >
        sudo apt-get update -y &&
        sudo apt-get install -y build-essential &&
        sudo apt-get install -y libopenmpi-dev openmpi-bin libomp-dev
    - name: compile pRIblast
      run: make -j4
      working-directory: ${{ github.workspace }}
